<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Registeration_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>38299bb9-dca3-4b3d-af9c-cf729d88c42e</testSuiteGuid>
   <testCaseLink>
      <guid>a68853fe-071d-42bc-8cf7-9ea90f16dfa9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 01 _ RegisterWithoutAllMandatoryFields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9be03225-856c-49ff-a2ac-443cce5be012</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7286d0d-a9f5-44fe-953d-fc1b39025520</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9841e835-3ed6-49e1-91dc-36ac513cab21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 02 _ RegisterWithoutFirstname</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d952a1a-7fc5-4705-9b0c-d04b5307a65e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ace6bdb1-1955-4fad-a2c3-78a176a3d1f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bb3b583-a904-4337-9dea-9cee1d4d8728</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 03 _ RegisterWithoutLastname</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7954494-28bf-40dd-b92e-4add91665574</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e126f6e-0e09-4099-b164-bd7e0b21c78d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36069016-0077-4ec0-b64d-7353932d0817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 04 _ RegisterWithoutEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29ff2be1-7f49-4b19-ac4b-d5555f3c25a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4945bad3-8bac-40e7-b8b3-6efef9630e33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5b3b844-0239-41d3-94a4-efdd0b6b9dd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 05 _ RegisterWithoutPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a316164-5ac8-46d9-8f16-04a73171cc0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cce2707e-e1e5-41f0-8be7-2694b502fddd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae93402e-ecca-421a-b55c-28988bb2b25c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 06 _ RegisterWithoutConfirmPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>689e0b34-898f-4fac-b1da-f528ed2f8b1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f3f4cf8-2fb5-4fb9-90e5-7e777ec5201b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2136e54f-71cd-42c0-84bc-a87b3ab34892</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 07 _ RegisterWithDifferentConfirmPassword</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1cf3a0f-2738-4aa9-b73d-4d80d8833365</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71935ccd-d7d0-4a90-8624-f32553ecab9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>403dd593-85ea-4849-8e55-319258817c5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registeration Test Cases/TC 08 _ RegisterWithValidData</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a3d8451-41b2-4ec5-a6f2-a927ee90e874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>291b1620-2aa7-4628-8c7d-3df1f418a210</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
