<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payment_method_continue_btn</name>
   <tag></tag>
   <elementGuidId>f995784f-00f0-4468-addf-ea2ace304964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-method-buttons-container > button[name=&quot;save&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-method-buttons-container']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69c2af72-8b84-4fc3-9562-9950fc35ed3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b475e84-4c01-43e9-a733-c0beda55217b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>1ae964ea-6e5a-4cb8-8c83-16c45d893d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 payment-method-next-step-button</value>
      <webElementGuid>192535c7-88ef-4cf0-85bc-b651265aadc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; PaymentMethod.save()</value>
      <webElementGuid>62fc056b-9f23-4781-a1c4-60e621fc81bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>5949f528-2642-45b3-85bd-1babc7417328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method-buttons-container&quot;)/button[@class=&quot;button-1 payment-method-next-step-button&quot;]</value>
      <webElementGuid>0a321ff6-dc12-43eb-a1c2-78c2d5e7e129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='save'])[2]</value>
      <webElementGuid>e3e99f72-64f9-4cfc-ae9e-65ba1ca83a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-method-buttons-container']/button</value>
      <webElementGuid>78384978-3ea5-49eb-94f6-196bf47d5e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[3]/following::button[1]</value>
      <webElementGuid>cc87a67a-e450-41d6-80e5-8916951e7425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay by credit / debit card'])[1]/following::button[1]</value>
      <webElementGuid>a90c27dd-d6b7-4dd2-bb9d-acc329263928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment information'])[1]/preceding::button[1]</value>
      <webElementGuid>95da539f-ba7b-4252-987b-70f17298c1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment is not required'])[1]/preceding::button[1]</value>
      <webElementGuid>10095d64-7de0-4dc3-9daa-884c2ec9770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/div/button</value>
      <webElementGuid>4ae95c6d-bb58-4db5-b1a7-19038e698826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'save' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>5018e0d7-52f9-4854-9e1e-8e45f8568cea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
