<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payment_info_continue_btn</name>
   <tag></tag>
   <elementGuidId>efdabf2c-d4d0-49d8-a6f0-1dc437be1ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-1.payment-info-next-step-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-info-buttons-container']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52e7eeca-02c2-48e3-a909-be3aed2a8731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a71f909e-7512-4371-b67c-57eb9c1ddef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 payment-info-next-step-button</value>
      <webElementGuid>ea3fa7bd-86be-4cf9-b344-bb9a2c2729bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; PaymentInfo.save()</value>
      <webElementGuid>a5511b2f-5522-43ed-9663-d18b66cc9ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>418ae3ad-7067-4178-afeb-e1b6a0409772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-info-buttons-container&quot;)/button[@class=&quot;button-1 payment-info-next-step-button&quot;]</value>
      <webElementGuid>1a7651b3-f743-43a1-98c3-97cd7b7c6164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>257bb3e6-f5fd-407a-b79e-963ce89ea0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-info-buttons-container']/button</value>
      <webElementGuid>4acc4cb2-a20e-4e3c-8b88-945a46d1b8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[4]/following::button[1]</value>
      <webElementGuid>e9db1c39-6cb3-4da2-955c-4df7d5d45250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USA'])[1]/following::button[1]</value>
      <webElementGuid>d1481865-3e88-4435-b80a-4ddf4bf2fed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm order'])[1]/preceding::button[1]</value>
      <webElementGuid>43df22a5-cdba-4a38-99e8-185eeacd67c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[5]/preceding::button[1]</value>
      <webElementGuid>308a265c-40ba-4b58-be92-ff6ac6b0a280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div[2]/div/button</value>
      <webElementGuid>1c63d218-02d4-4207-bc5d-e4aadcd04877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>5b78ad38-9ab3-44d6-a228-d2ae620c4d58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
