<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phone_number_field</name>
   <tag></tag>
   <elementGuidId>76949fcb-7a87-47d5-a781-b98a5ab9b17a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BillingNewAddress_PhoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BillingNewAddress_PhoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bff0ff27-189e-4d73-b74e-f7af87747020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>7db61968-6b9a-4e3f-a3da-a3db14f7d03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>363ae673-c20d-4f33-96c6-482bb1f28e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Phone is required</value>
      <webElementGuid>e3f35ede-d063-4059-9c52-4a7308e104d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BillingNewAddress_PhoneNumber</value>
      <webElementGuid>eb705a3c-b79f-433a-938c-d7b196e560c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BillingNewAddress.PhoneNumber</value>
      <webElementGuid>ea3b9a8f-3a53-439d-b1fb-4f19230b8dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BillingNewAddress_PhoneNumber&quot;)</value>
      <webElementGuid>834104d3-7ad4-4645-aaf5-447c3cc4b356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BillingNewAddress_PhoneNumber']</value>
      <webElementGuid>5760b585-317c-4612-a9e5-6e05d51ea650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div[11]/input</value>
      <webElementGuid>78d557c7-3de5-42d8-ad6a-4c5f9b8e75b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>0dd1cea2-4731-4382-b543-915cefafa022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'BillingNewAddress_PhoneNumber' and @name = 'BillingNewAddress.PhoneNumber']</value>
      <webElementGuid>1cc95658-f833-4b07-bc49-a7d6e766d1fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
