<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>postal_code_field</name>
   <tag></tag>
   <elementGuidId>36b316a8-6418-45ab-923f-68975fb2664a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BillingNewAddress_ZipPostalCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BillingNewAddress_ZipPostalCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe5d836c-c8b8-4dbc-8796-b119849ac9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34724a01-0f57-4feb-8450-08a3b071bfd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39ddb648-ce80-4169-b714-d967212d172b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Zip / postal code is required</value>
      <webElementGuid>f54e10b0-8560-41eb-8223-036196891865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BillingNewAddress_ZipPostalCode</value>
      <webElementGuid>9b0d4af9-cf11-4465-b8f5-60a795b77614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BillingNewAddress.ZipPostalCode</value>
      <webElementGuid>9faa9341-1c6d-419b-aaf3-29145dff2f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BillingNewAddress_ZipPostalCode&quot;)</value>
      <webElementGuid>cfa7dcde-9f08-4bbb-b548-5d30fe4b3c05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BillingNewAddress_ZipPostalCode']</value>
      <webElementGuid>3745c9de-c2fb-491a-af1f-3322d1f73799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billing-new-address-form']/div/div/div[10]/input</value>
      <webElementGuid>e433a469-e7ca-4964-b602-31855c28b39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>6259577e-9797-4ef4-932c-2b9293867ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'BillingNewAddress_ZipPostalCode' and @name = 'BillingNewAddress.ZipPostalCode']</value>
      <webElementGuid>9a4635fe-2634-4d88-b5cc-970d78a63a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
