<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selected_country</name>
   <tag></tag>
   <elementGuidId>30ccd5e6-9566-422a-8d4c-8f9dca9df13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.product-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='BillingNewAddress_CountryId']//option[@value='211']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b586a339-5b90-48be-8593-90733358f729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lenovo-ideacentre-600-all-in-one-pc</value>
      <webElementGuid>bf323155-5a62-4e3c-a188-97f91c08ed57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>bb06c883-8c9f-4c53-bcf5-78175cb27ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lenovo IdeaCentre 600 All-in-One PC</value>
      <webElementGuid>8e81378f-82b1-4761-8315-5ef72cd1d020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;cart&quot;]/tbody[1]/tr[1]/td[@class=&quot;product&quot;]/a[@class=&quot;product-name&quot;]</value>
      <webElementGuid>8bb48544-ee7d-4168-8663-a4cab39e09d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/table/tbody/tr/td[3]/a</value>
      <webElementGuid>d01b211d-dc92-446e-a94d-5ae7b857fda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lenovo IdeaCentre 600 All-in-One PC')])[2]</value>
      <webElementGuid>0435ee24-f813-42f2-94cc-6558def6d26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LE_IC_600'])[1]/following::a[2]</value>
      <webElementGuid>876824f6-d043-4457-a66b-d9617f681bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU:'])[1]/following::a[2]</value>
      <webElementGuid>607bb24f-ad2d-4a1d-9041-698f13e23218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price:'])[1]/preceding::a[1]</value>
      <webElementGuid>8db9a17d-d125-43e2-95c1-d286eb09c26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$500.00'])[2]/preceding::a[1]</value>
      <webElementGuid>3fdf6070-7a71-4c38-9e78-03d8f3fdaed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/lenovo-ideacentre-600-all-in-one-pc')])[4]</value>
      <webElementGuid>0b3ea187-5780-4c84-a393-151a9319c149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>0e71a15d-54cb-4a81-b51b-c0eccb5a8045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lenovo-ideacentre-600-all-in-one-pc' and (text() = 'Lenovo IdeaCentre 600 All-in-One PC' or . = 'Lenovo IdeaCentre 600 All-in-One PC')]</value>
      <webElementGuid>7f48675b-ab0a-4a48-acdb-7e43bd408ae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
