<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_password_error_msg</name>
   <tag></tag>
   <elementGuidId>270fbbf9-e4bc-4ea1-8197-3fa789a10c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ConfirmPassword-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ConfirmPassword-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2cf8066-da6b-4e30-a7a7-0c04906f068f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConfirmPassword-error</value>
      <webElementGuid>0bac3034-fd11-4fe8-ace1-52087e0f733c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The password and confirmation password do not match.</value>
      <webElementGuid>f82238e3-34ec-4e7e-aa9f-405611484e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConfirmPassword-error&quot;)</value>
      <webElementGuid>b1275053-5fbb-40d8-a1ec-bad6f018d1b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ConfirmPassword-error']</value>
      <webElementGuid>eb7d12cd-57c8-4350-a9f2-5f842a8b19cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[2]</value>
      <webElementGuid>b65a4941-cd60-4385-9b94-bb97abf4ad59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm password:'])[1]/following::span[3]</value>
      <webElementGuid>d84fbcf3-7e6b-4862-8cef-b3bccbbecba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[3]/preceding::span[1]</value>
      <webElementGuid>4ce7dfcb-d974-4b70-8856-9d913db82b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/preceding::span[1]</value>
      <webElementGuid>611935f0-2985-4351-a2f1-3f91eee08d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The password and confirmation password do not match.']/parent::*</value>
      <webElementGuid>b6973dc6-abf3-4beb-89ee-8462603ac179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/span[2]/span</value>
      <webElementGuid>be36ae2a-45a7-4b40-8ac0-dda7df041a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ConfirmPassword-error' and (text() = 'The password and confirmation password do not match.' or . = 'The password and confirmation password do not match.')]</value>
      <webElementGuid>8571ef7d-9e42-46ee-aed9-fee06fd72b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
