<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>empty_password_error_msg</name>
   <tag></tag>
   <elementGuidId>3bf254f5-fb9b-4349-83d9-48a0b6a1bac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Password-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Password-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>da4d1dcd-0655-4ec1-8138-476c204b3574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password-error</value>
      <webElementGuid>6e0173e4-e858-4ffe-903b-70acec0ffd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password is required.</value>
      <webElementGuid>390cb053-c0b8-4edc-8d55-911fe1e7a664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Password-error&quot;)</value>
      <webElementGuid>a7c75920-07dc-4339-9b9d-6c94aa8e389e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Password-error']</value>
      <webElementGuid>27d62cbc-a12e-4c25-83c7-d667ee33059e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[2]</value>
      <webElementGuid>79fce5b9-46b0-41fd-a46b-fc653d72dccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::span[3]</value>
      <webElementGuid>f44c4137-f5cb-447d-8b4c-84422a855909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm password:'])[1]/preceding::span[1]</value>
      <webElementGuid>8b941802-3d14-43be-81fb-3c214c8797ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::span[1]</value>
      <webElementGuid>d2e19b85-74c0-43cd-8638-0179b8d5d177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password is required.']/parent::*</value>
      <webElementGuid>d932a137-5486-47ca-8f8b-f5120c51e7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>0aef8e24-f877-4507-ac8f-cf00924419b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Password-error' and (text() = 'Password is required.' or . = 'Password is required.')]</value>
      <webElementGuid>0eba84c8-d803-470d-b381-19a2cae03a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
