<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lenovo_600_product</name>
   <tag></tag>
   <elementGuidId>356f6897-75d2-4bf8-b485-9c5e433aa6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.product-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(@href, '/lenovo-ideacentre-600')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3ba312f-dec4-4fcf-b673-9d40f38ae5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lenovo-ideacentre-600-all-in-one-pc</value>
      <webElementGuid>1aaab8d3-03a9-4a66-af34-8d1c2cf00630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lenovo IdeaCentre 600 All-in-One PC</value>
      <webElementGuid>a8d24b79-114b-487c-90c0-8481a51f2660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-form&quot;)/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;cart&quot;]/tbody[1]/tr[1]/td[@class=&quot;product&quot;]/a[@class=&quot;product-name&quot;]</value>
      <webElementGuid>cc027840-df12-496e-8c65-7ec9e2754008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>041ce8a9-c377-4233-b568-016906cb4e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div/table/tbody/tr/td[3]/a</value>
      <webElementGuid>d6133a08-cf33-4221-9e63-06e4ea3ebcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lenovo IdeaCentre 600 All-in-One PC')])[2]</value>
      <webElementGuid>d3eb21f9-4e3e-445a-b961-3134c0d1462b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LE_IC_600'])[1]/following::a[2]</value>
      <webElementGuid>839f251a-e40b-4376-8245-c4bcf0d76101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU:'])[1]/following::a[2]</value>
      <webElementGuid>cac1c0d8-8434-4968-8335-5a1859dc4a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price:'])[1]/preceding::a[1]</value>
      <webElementGuid>ab6f4291-d635-4cd7-a3db-cf974c9a859f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$500.00'])[2]/preceding::a[1]</value>
      <webElementGuid>4958b1d2-a085-49c4-9586-fdb9610f93f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/lenovo-ideacentre-600-all-in-one-pc')])[4]</value>
      <webElementGuid>5cc83197-8f92-4692-a5be-d542f21807be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>0cca62e2-1be7-4785-8d8e-c431bc7d7322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lenovo-ideacentre-600-all-in-one-pc' and (text() = 'Lenovo IdeaCentre 600 All-in-One PC' or . = 'Lenovo IdeaCentre 600 All-in-One PC')]</value>
      <webElementGuid>a148b437-00fc-49bd-9dda-126d0a08fc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lenovo IdeaCentre 600 All-in-One PC')]</value>
      <webElementGuid>1c9f6c83-0cc4-4870-b3b5-a49b95d9df84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to wishlist'])[2]/following::a[2]</value>
      <webElementGuid>f9c48ecb-f972-4348-b631-b5cf743656ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to compare list'])[2]/following::a[2]</value>
      <webElementGuid>cc65ff06-63f0-49f2-a3ff-a2bba8ad5266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$500.00'])[1]/preceding::a[1]</value>
      <webElementGuid>34a7ab2c-9f10-492f-85a2-b94a1d7eb0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[3]/preceding::a[1]</value>
      <webElementGuid>df32b21d-62bb-4e43-8ac7-5fcc5f9c51ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lenovo IdeaCentre 600 All-in-One PC']/parent::*</value>
      <webElementGuid>5dcbcb66-e69d-43f4-a0d4-be5de20f086c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/lenovo-ideacentre-600-all-in-one-pc')])[2]</value>
      <webElementGuid>d7d17658-3394-470f-bf1b-b3aedcd6aed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/h2/a</value>
      <webElementGuid>70daba56-6a7e-4790-b630-09d98f6a58a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
